export const SYSTEM_CONSTANTS = {
  APP_NAME: 'مصنع النجار للأثاث - Smart Factory ERP',
  DEFAULT_CURRENCY: 'ج.م',
  PAGINATION: {
    DEFAULT_PAGE_SIZE: 50,
    MAX_PAGE_SIZE: 200,
  },
  FIRESTORE_COLLECTIONS: {
    USERS: 'users',
    SETTINGS: 'settings',
    WAREHOUSES: 'warehouses',
    ITEMS: 'items',
    SUPPLIERS: 'suppliers',
    PURCHASES: 'purchases',
    ISSUANCES: 'issuances',
    WORK_ORDERS: 'furnitureWorkOrders',
    PRODUCTION_JOBS: 'productionJobs',
    SAFES: 'safes',
    SAFE_TRANSACTIONS: 'safeTransactions',
    CUSTOMERS: 'customers',
    SALES_ORDERS: 'salesOrders',
    EMPLOYEES: 'employees',
    ATTENDANCE: 'attendance',
    PAYROLLS: 'payrolls',
    AUDIT_LOGS: 'auditLogs',
  },
  WORK_ORDER_STAGES: [
    'النجارة',
    'التنعيم والصنفرة',
    'الدهانات والرش',
    'التنجيد والقص',
    'التجميع النهائي والتشطيب',
  ] as const,
  WORK_ORDER_STATUSES: [
    'جديد',
    'قيد التنفيذ',
    'معلق',
    'جاهز للتسليم',
    'تم التسليم',
    'ملغى',
  ] as const,
} as const;
