import { UserPermissions, UserRole } from '../types';

export const ROLE_PERMISSIONS: Record<UserRole, UserPermissions> = {
  super_admin: {
    dashboard: true,
    inventory: true,
    production: true,
    sales: true,
    purchases: true,
    finance: true,
    hr: true,
    reports: true,
    settings: true,
    users: true,
    maintenance: true,
    suppliers: true,
    vehicles: true,
    showroom: true,
    canDelete: true,
  },
  admin: {
    dashboard: true,
    inventory: true,
    production: true,
    sales: true,
    purchases: true,
    finance: true,
    hr: true,
    reports: true,
    settings: true,
    users: true,
    maintenance: true,
    suppliers: true,
    vehicles: true,
    showroom: true,
    canDelete: true,
  },
  manager: {
    dashboard: true,
    inventory: true,
    production: true,
    sales: true,
    purchases: true,
    finance: true,
    hr: true,
    reports: true,
    settings: false,
    users: false,
    maintenance: true,
    suppliers: true,
    vehicles: true,
    showroom: true,
    canDelete: false,
  },
  finance: {
    dashboard: true,
    inventory: true,
    production: false,
    sales: true,
    purchases: true,
    finance: true,
    hr: true,
    reports: true,
    settings: false,
    users: false,
    maintenance: false,
    suppliers: true,
    vehicles: true,
    showroom: true,
    canDelete: false,
  },
  accountant: {
    dashboard: true,
    inventory: true,
    production: false,
    sales: true,
    purchases: true,
    finance: true,
    hr: true,
    reports: true,
    settings: false,
    users: false,
    maintenance: false,
    suppliers: true,
    vehicles: false,
    showroom: false,
    canDelete: false,
  },
  inventory: {
    dashboard: true,
    inventory: true,
    production: true,
    sales: false,
    purchases: true,
    finance: false,
    hr: false,
    reports: true,
    settings: false,
    users: false,
    maintenance: false,
    suppliers: true,
    vehicles: false,
    showroom: true,
    canDelete: false,
  },
  warehouse: {
    dashboard: false,
    inventory: true,
    production: true,
    sales: false,
    purchases: true,
    finance: false,
    hr: false,
    reports: false,
    settings: false,
    users: false,
    maintenance: false,
    suppliers: false,
    vehicles: false,
    showroom: false,
    canDelete: false,
  },
  purchasing: {
    dashboard: true,
    inventory: true,
    production: false,
    sales: false,
    purchases: true,
    finance: true,
    hr: false,
    reports: true,
    settings: false,
    users: false,
    maintenance: false,
    suppliers: true,
    vehicles: false,
    showroom: false,
    canDelete: false,
  },
  sales: {
    dashboard: true,
    inventory: true,
    production: false,
    sales: true,
    purchases: false,
    finance: false,
    hr: false,
    reports: true,
    settings: false,
    users: false,
    maintenance: false,
    suppliers: false,
    vehicles: false,
    showroom: true,
    canDelete: false,
  },
  production: {
    dashboard: true,
    inventory: true,
    production: true,
    sales: false,
    purchases: false,
    finance: false,
    hr: true,
    reports: true,
    settings: false,
    users: false,
    maintenance: true,
    suppliers: false,
    vehicles: true,
    showroom: false,
    canDelete: false,
  },
  hr: {
    dashboard: true,
    inventory: false,
    production: false,
    sales: false,
    purchases: false,
    finance: true,
    hr: true,
    reports: true,
    settings: false,
    users: false,
    maintenance: false,
    suppliers: false,
    vehicles: false,
    showroom: false,
    canDelete: false,
  },
  maintenance: {
    dashboard: true,
    inventory: false,
    production: true,
    sales: false,
    purchases: false,
    finance: false,
    hr: false,
    reports: true,
    settings: false,
    users: false,
    maintenance: true,
    suppliers: false,
    vehicles: true,
    showroom: false,
    canDelete: false,
  },
  reports: {
    dashboard: true,
    inventory: true,
    production: true,
    sales: true,
    purchases: true,
    finance: true,
    hr: true,
    reports: true,
    settings: false,
    users: false,
    maintenance: true,
    suppliers: true,
    vehicles: true,
    showroom: true,
    canDelete: false,
  },
  showroom: {
    dashboard: true,
    inventory: true,
    production: false,
    sales: true,
    purchases: false,
    finance: false,
    hr: false,
    reports: true,
    settings: false,
    users: false,
    maintenance: false,
    suppliers: false,
    vehicles: false,
    showroom: true,
    canDelete: false,
  },
  worker: {
    dashboard: false,
    inventory: false,
    production: true,
    sales: false,
    purchases: false,
    finance: false,
    hr: false,
    reports: false,
    settings: false,
    users: false,
    maintenance: false,
    suppliers: false,
    vehicles: false,
    showroom: false,
    canDelete: false,
  },
};

export function hasPermission(
  userRole?: UserRole | string,
  userPermissions?: UserPermissions,
  requiredDomain?: keyof UserPermissions
): boolean {
  if (!requiredDomain) return true;
  
  // Super Admin and Admin override
  if (userRole === 'super_admin' || userRole === 'admin') return true;

  // Custom explicit permission check
  if (userPermissions && typeof userPermissions[requiredDomain] === 'boolean') {
    return userPermissions[requiredDomain] === true;
  }

  // Role default permission fallback
  if (userRole && userRole in ROLE_PERMISSIONS) {
    return ROLE_PERMISSIONS[userRole as UserRole][requiredDomain] === true;
  }

  return false;
}
